name: Deploy Blog

on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: '12'
            - name: Check Buildability
              run: yarn build
            - name: Run Blog
              uses: appleboy/ssh-action@master
              with:
                  host: ${{secrets.HOST}}
                  username: ${{secrets.USERNAME}}
                  key: ${{secrets.KEY}}
                  port: ${{secrets.PORT}}
                  script: |
                      cd ~/beleap-blog
                      git pull
                      yarn
                      yarn build
                      yarn start
