name: Deploy Blog

on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Login to docker hub
              uses: actions-hub/docker/login@master
              env:
                  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build :latest
              run: docker build -t beleap/beleap-blog:latest .

            - name: Push to docker hub :latest
              uses: actions-hub/docker@master
              with:
                  args: push beleap/beleap-blog:latest
            - name: Run Blog
              uses: appleboy/ssh-action@master
              with:
                  host: ${{secrets.HOST}}
                  username: ${{secrets.USERNAME}}
                  key: ${{secrets.KEY}}
                  port: ${{secrets.PORT}}
                  timeout: 200m
                  script: |
                      echo "if [ -z \$(docker ps --all | grep beleap-blog)]" > run.sh
                      echo "then" >> run.sh
                      echo "    docker rm --force beleap-blog" >> run.sh
                      echo "else" >> run.sh
                      echo "    echo  \"Running container not found\"" >> run.sh
                      echo "fi" >> run.sh
                      echo "docker run -d --restart=always -p 8080:3000 --name beleap-blog beleap/beleap-blog" >> run.sh
                      chmod +x ./run.sh
                      ./run.sh
